- name: install-qemu-quest-agent 
  hosts: all
  become: true
  tasks:
    - name: install-qemu-guest-agent
      apt:
        name: qemu-guest-agent
        state: present
        update_cache: true

    - name: enable-qemu-guest-agent
      ansible.builtin.shell: "systemctl start qemu-guest-agent"
    
    - name: enable-qemu-guest-agent
      ansible.builtin.shell: "systemctl enable qemu-guest-agent"


        
      
