- name: install-ufw
  hosts: all
  become: yes
  tasks:
    - name: update-apt-install-pkg
      apt:
        name:  
          - ufw
        state: latest
        update_cache: true

    - name: ufw-enabled
      community.general.ufw:
        state: "enabled"
        policy: "deny"
        logging: "on"

    - name: ufw-rules
      community.general.ufw:
        rule: "allow"
        port: "{{ item }}"  
        proto: "tcp"
      with_items: 
        - "22"
        - "80"
        - "443"